select * from ADDRESS;
select * from CUSTOMER;


-- LIST ALL CUSTOMERS WHO LIVE IN TEXAS HAVING ISSUES WITH THIS***
SELECT CUSTOMER.CUSTOMER_ID, FIRST_NAME, LAST_NAME, ADDRESS.address_id, ADDRESS.DISTRICT
FROM CUSTOMER
JOIN ADDRESS ON address.address_id  = customer.address_id 
WHERE ADDRESS.DISTRICT LIKE 'TEXAS%';


-- GET ALL PAYMENTS ABOVE 6.99 W/ CUSTOMER FULL NAME
select * from CUSTOMER;
select * from PAYMENT;


SELECT CUSTOMER.CUSTOMER_ID, LAST_NAME, FIRST_NAME, AMOUNT
FROM PAYMENT
JOIN CUSTOMER ON CUSTOMER.customer_id = PAYMENT.customer_id
WHERE AMOUNT > 6.99;


-- SHOW ALL CUSTOMERS WHO HAVE MADE PAYMENTS OVER 175 --CHANGE TO SHOW AMOUNT
select * from payment ;
select * from customer ;

select CUSTOMER_ID, FIRST_NAME, LAST_NAME
from customer 
where CUSTOMER_ID in (
	select CUSTOMER_ID
	from PAYMENT
	group by customer_id 
	having SUM(AMOUNT) > 175
	order by SUM(AMOUNT) DESC
)

group by customer_id, first_name, LAST_NAME;


-- LIST ALL CUSTOMERS THAT LIVE IN NEPAL
-- NEPAL COUNTRY_ID = 66
select * from CITY; -- NEED to get to COUNTRY ID 
select * from COUNTRY; --COUNTRY_ID is in CITY ID 
select * from customer ; -- ADDRESS ID is in CUSTOMER  
select * from address ; -- CITY_ID is in ADDRESS

SELECT C.FIRST_NAME, C.LAST_NAME
FROM CUSTOMER AS C
JOIN ADDRESS AS A ON C.ADDRESS_ID = A.ADDRESS_ID
JOIN CITY AS CI ON A.CITY_ID = CI.CITY_ID
JOIN COUNTRY AS CO ON CI.COUNTRY_ID = CO.COUNTRY_ID
WHERE CO.COUNTRY_ID = 66;

--WHICH STAFF MEMBER HAD THE MOST TRANSACTIONS
-- NEED TO JOIN PAYMENT & STAFF
-- SEARCH FOR COUNT OF RENTAL_ID GROUP BY STAFF ID ORRDER BY ASC

select * from payment
SELECT PAYMENT.STAFF_ID, STAFF.first_name, STAFF.last_name, COUNT(PAYMENT.rental_id) AS rental_count
FROM PAYMENT 
FULL JOIN STAFF 
ON PAYMENT.STAFF_ID = STAFF.STAFF_ID 
GROUP BY PAYMENT.STAFF_ID, STAFF.first_name, STAFF.last_name
ORDER BY rental_count DESC;

-- HOW MANY MOVIES OF EACH RATING ARE THERE?
-- 
select * from FILM
SELECT RATING, COUNT(*) AS MOVIE_COUNT
FROM FILM
GROUP BY RATING;


--SHOW ALL CUSTOMERS WHO HAVE MADE A SINGLE PAYMENT ABOVE 6.99
-- USE SUBQUERRIES
--** NEED HELP
SELECT first_name , last_name 
FROM CUSTOMER
WHERE CUSTOMER_ID IN (
    SELECT CUSTOMER_ID
    FROM PAYMENT
    GROUP BY CUSTOMER_ID
    HAVING COUNT(*) = 1 AND MAX(AMOUNT) > 6.99
);

-- HOW MANY FREE RENTALS DID OUR STORE GIVE OUT
select COUNT(AMOUNT) as FREE_RENTAL
from PAYMENT
where AMOUNT = 0.00
